name: water_tracking
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.4.beta
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  archive: 3.6.1
  logger: 2.5.0
  path: 1.9.0
  path_provider: 2.1.5
  shared_preferences: 2.3.3
  device_info_plus: 11.1.1
  package_info_plus: 8.1.1
  dynamic_color: 1.7.0
  uuid: 4.5.1
  isar: 4.0.0-dev.14
  isar_flutter_libs: 4.0.0-dev.14
  get: 5.0.0-release-candidate-9.2.1
  fluttertoast: 8.2.8
  flutter_displaymode: 0.6.0
  bitsdojo_window: 0.1.6



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  generate: true
  uses-material-design: true

